name: "pull"
version: "0.0.1"
usage: "Please see xxx for usage"
description: "Pull chart package"
command: "$HELM_PLUGIN_DIR/bin/helmpull"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"